name = "Create- WAR"
author = "Chaneriel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd37c9e3427f625f94923bdb197cee011fe4f21a472e861f70d17d8f2f31ba4c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
